=== bchivers-stanford/beyond_the_paywall/schemas/pageNav.1.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$comment": "Please do not edit this schema by hand. Generate it instead by running npm run build:schema.",
  "mozPipelineMetadata": {
    "expiration_policy": {
      "delete_after_days": 558
    }
  },
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "description": "the type of event recorded. Either WebScience.advertisements, WebScience.articleContents, WebScience.pageNav, or WebScience.pageNavSensitive",
      "enum": [
        "WebScience.advertisements",
        "WebScience.articleContents",
        "WebScience.pageNav",
        "WebScience.pageNavSensitive",
        "WebScience.totalTiming"
      ]
    },
    "userId": {
      "type": "string",
      "description": "a unique ID associated with a participant."
    },
    "visitId": {
      "type": "string",
      "description": "a unique ID associated with a page visit."
    },
    "referrer": {
      "type": "string",
      "description": "The page that referred the user to the current page"
    },
    "pageVisitStartTime": {
      "type": "integer",
      "description": "unix timestamp (in ms) of the page visit start"
    },
    "pageVisitStopTime": {
      "type": "integer",
      "description": "unix timestamp (in ms) of the page visit end. NOTE: this field will not necessarily represent the page visit stop time, just the largest time value at the time of the event creation. For a given page id, look for the largest value of pageVisitStopTime to get more accurate information."
    },
    "attentionDuration": {
      "type": "integer",
      "description": "duration (in ms) that the page was in attentive view"
    },
    "audioDuration": {
      "type": "integer",
      "description": "duration (in ms) that audio was playing on the page"
    },
    "attentionAndAudioDuration": {
      "type": "integer",
      "description": "duration (in ms) that audio was playing on the page and the page was in attentive view"
    },
    "maxRelativeScrollDepth": {
      "type": "number",
      "description": "The largest depth reach on the page, as a proportion of the total page height"
    },
    "url": {
      "type": "string",
      "description": "The URL of the page visited"
    }
  },
  "required": [
    "type",
    "visitId",
    "userId",
    "url",
    "referrer",
    "pageVisitStartTime",
    "pageVisitStopTime",
    "attentionDuration",
    "audioDuration",
    "attentionAndAudioDuration",
    "maxRelativeScrollDepth"
  ]
}

=== bchivers-stanford/beyond_the_paywall/schemas/pageNav-example.json
{
  "type": "WebScience.pageNav",
  "userId": "7a367510-5fcc-4313-b70f-117fa3e2f027",
  "visitId": "4caccb6e-7ae8-42e8-bd3c-c6253713801a",
  "url": "https://www.yourbigsky.com/",
  "referrer": "",
  "pageVisitStartTime": 1623271436192,
  "pageVisitStopTime": 1623271449198,
  "attentionDuration": 12520,
  "audioDuration": 0,
  "attentionAndAudioDuration": 0,
  "maxRelativeScrollDepth": 0.21491891891891893
}
